# Generated by Django 5.2.12 on 2026-03-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
